# Generated by Django 6.0.3 on 2026-07-15 06:28

import localflavor.ir.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[localflavor.ir.forms.IRPostalCodeField.clean], verbose_name='کد پستی'),
        ),
    ]
