# Generated by Django 6.0.3 on 2026-07-13 02:37

import django.db.models.deletion
import store.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('store_name', models.CharField(max_length=255, verbose_name='اسم فروشگاه')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logo/', validators=[store.validators.validate_file_size], verbose_name='لوگوی فروشگاه')),
                ('store_phone', models.CharField(max_length=20, unique=True, verbose_name='شماره تماس فروشگاه')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن فروشگاه')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='مالک فروشگاه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
