# Generated by Django 6.0.3 on 2026-07-13 16:04

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن فروشگاه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logo/%Y/%m/%d/', validators=[store.validators.validate_file_size], verbose_name='لوگوی فروشگاه'),
        ),
    ]
