# Generated by Django 6.0.3 on 2026-07-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_is_active_alter_store_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن فروشگاه'),
        ),
    ]
