# Generated by Django 6.0.3 on 2026-07-14 14:54

import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصویر محصولات'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m/%d/', validators=[product.validators.validate_file_size], verbose_name='تصویر محصول'),
        ),
    ]
