# Generated by Django 6.0.3 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'خریدار'), ('seller', 'فروشنده'), ('staff', 'ادمین')], default='customer', max_length=10, verbose_name='نقش'),
        ),
    ]
